---
- name: Validar y Recargar Nginx
  block:
    - name: Verificar sintaxis de configuración de Nginx
      command: nginx -t
      changed_when: false

    - name: Recargar Nginx sin caída de servicio (Graceful Reload)
      service:
        name: nginx
        state: reloaded