name: "Pipeline IaC: Destroy Infrastructure"

on:
  workflow_dispatch:

jobs:
  destroy_iac:
    name: "Destrucción de Infraestructura"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./iac

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # --- AÑADE ESTO TAMBIÉN AQUÍ ---
      - name: Generar clave SSH temporal para AWS
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/aws_ansible_key -N ""

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve